cmake_minimum_required( VERSION 3.20 )

if ( NOT DEFINED VEX_FACTORY_ASSET_DIR OR VEX_FACTORY_ASSET_DIR STREQUAL "" )
    get_filename_component( VEX_FACTORY_ASSET_DIR
        "${CMAKE_CURRENT_LIST_DIR}/../../temp/vexfactory/assets" ABSOLUTE )
endif()

# Kenney Tiny Factory 1.0, CC0. Keep the original License.txt in the download.
set( asset_url "https://kenney.nl/media/pages/assets/tiny-factory/1652277319-1788860879/kenney_tiny-factory.zip" )
set( asset_sha256 "eaec4169aa4bf3ea7cec4be2b06147b1a02e54bdbe61d49d4568df7e57b0db2a" )
file( MAKE_DIRECTORY "${VEX_FACTORY_ASSET_DIR}" )
set( archive "${VEX_FACTORY_ASSET_DIR}/kenney_tiny-factory-1.0.zip" )
set( cached_hash "" )
if ( EXISTS "${archive}" )
    file( SHA256 "${archive}" cached_hash )
endif()
if ( NOT cached_hash STREQUAL asset_sha256 )
    message( STATUS "Download Kenney Tiny Factory 1.0 (CC0, about 90 KB)" )
    file( DOWNLOAD "${asset_url}" "${archive}.part"
        TLS_VERIFY ON TIMEOUT 60 INACTIVITY_TIMEOUT 20 STATUS download_status )
    list( GET download_status 0 download_code )
    list( GET download_status 1 download_message )
    if ( NOT download_code EQUAL 0 )
        file( REMOVE "${archive}.part" )
        message( FATAL_ERROR "Asset download failed: ${download_message}. Run this command again to retry." )
    endif()
    file( SHA256 "${archive}.part" downloaded_hash )
    if ( NOT downloaded_hash STREQUAL asset_sha256 )
        file( REMOVE "${archive}.part" )
        message( FATAL_ERROR "Asset checksum mismatch. No artwork was extracted." )
    endif()
    file( RENAME "${archive}.part" "${archive}" )
endif()
file( ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${VEX_FACTORY_ASSET_DIR}" )
if ( NOT EXISTS "${VEX_FACTORY_ASSET_DIR}/Tilemap/tilemap_packed.png"
    OR NOT EXISTS "${VEX_FACTORY_ASSET_DIR}/License.txt" )
    message( FATAL_ERROR "The asset archive does not contain the expected tilemap and license." )
endif()
message( STATUS "VexFactory assets ready: ${VEX_FACTORY_ASSET_DIR}" )
