cmake_minimum_required( VERSION 3.20 )
foreach( required VEX_FACTORY_BINARY VEX_FACTORY_ASSET_DIR VEX_FACTORY_DIST_DIR RAYLIB_LICENSE GLFW_LICENSE )
    if ( NOT DEFINED ${required} OR "${${required}}" STREQUAL "" )
        message( FATAL_ERROR "Missing package argument: ${required}" )
    endif()
endforeach()
if ( NOT EXISTS "${VEX_FACTORY_BINARY}" OR NOT EXISTS "${VEX_FACTORY_ASSET_DIR}/Tilemap/tilemap_packed.png" )
    message( FATAL_ERROR "Build the game and fetch its artwork before packaging." )
endif()
if ( VEX_FACTORY_CONFIG STREQUAL "Debug" )
    message( WARNING "This is a Debug package. Use a Release build for distribution, especially on Windows." )
endif()
set( stage "${VEX_FACTORY_DIST_DIR}/VexFactory" )
# Never sweep an arbitrary non-owned folder into an archive (or delete it).
if ( EXISTS "${stage}/.vexfactory-package-stage" )
    file( REMOVE_RECURSE "${stage}" )
elseif ( EXISTS "${stage}" )
    message( FATAL_ERROR "Package staging directory is not owned by this script: ${stage}" )
endif()
file( MAKE_DIRECTORY "${stage}/assets/Tilemap" "${stage}/licenses" )
file( WRITE "${stage}/.vexfactory-package-stage" "VexFactory packaging owns this staging directory.\n" )
file( COPY "${VEX_FACTORY_BINARY}" DESTINATION "${stage}" )
file( COPY "${VEX_FACTORY_ASSET_DIR}/Tilemap/tilemap_packed.png" DESTINATION "${stage}/assets/Tilemap" )
file( COPY "${VEX_FACTORY_ASSET_DIR}/License.txt" DESTINATION "${stage}/assets" )
configure_file( "${RAYLIB_LICENSE}" "${stage}/licenses/raylib.txt" COPYONLY )
configure_file( "${GLFW_LICENSE}" "${stage}/licenses/glfw.txt" COPYONLY )
file( WRITE "${stage}/licenses/vecs.txt" "Vecs and VexFactory\nCopyright 2026 UAA Software\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the Software), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n" )
file( WRITE "${stage}/README.txt" "VexFactory: The Last Freight\n\nLaunch vex_factory.exe on Windows, or ./vex_factory on Linux and macOS.\nThe assets folder must remain next to the executable.\nSaves go to the operating system's user-data directory, not this folder.\n\nEnter continues your factory or opens the first dispatch.\nSpace launches or pauses production. F1 opens the field notes.\nCtrl/Cmd +/- changes interface text size. Wheel zooms the floor or scrolls a panel.\n\nThe game needs desktop OpenGL 3.3. Linux also needs the libc++ runtime.\nIf your ZIP tool removed executable permissions, run chmod +x vex_factory.\nThis is a platform-specific archive, not an installer or notarized application.\n\nArt: Kenney Tiny Factory (CC0). Fonts come from your operating system and are not included.\nLibrary license notices are in licenses/.\n" )
set( archive "${VEX_FACTORY_DIST_DIR}/VexFactory-${VEX_FACTORY_PLATFORM}.zip" )
execute_process( COMMAND "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip VexFactory
    WORKING_DIRECTORY "${VEX_FACTORY_DIST_DIR}" RESULT_VARIABLE result )
if ( NOT result EQUAL 0 )
    message( FATAL_ERROR "Cannot create the game archive." )
endif()
message( STATUS "VexFactory package: ${archive}" )
